site_name: TTIslaDeManJoelIglesias
nav:
    - Home: index.md
    - Historia: historia.md
    - Categorias: categorias.md
    - Ediciones Campeonato Munidal: ediciones.md
    - About: about.md 
theme: readthedocs
include_search_page: true

